version: "3.9"

services:

  node_app:
    container_name: node_app
    build: .
    ports:
      - "8000:3000"
    environment:
      - PG_DB=db-oak
      - PG_USER=postgres
      - PG_PASSWORD=12345
      - PG_HOST=db
    restart: always
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db-oak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}